#!/bin/sh
set -eu

ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/../../.." && pwd)
WATCH_COMPOSE="$ROOT/deployment/compose.watch.yaml"
PROJECT="geoguessme-watch-rehearsal-$$"
NETWORK="geoguessme-watch-production-$$"
TMP=$(mktemp -d)
chmod 0755 "$TMP"
MOCK_BACKEND="geoguessme-production-backend-rehearsal-$$"
MOCK_DEV="geoguessme-dev-backend-rehearsal-$$"

cleanup() {
    docker compose -p "$PROJECT" -f "$WATCH_COMPOSE" --project-directory "$ROOT" \
        down -v --remove-orphans >/dev/null 2>&1 || true
    docker rm -f "$MOCK_BACKEND" "$MOCK_DEV" >/dev/null 2>&1 || true
    docker network rm "$NETWORK" >/dev/null 2>&1 || true
    rm -rf "$TMP"
}
trap cleanup EXIT INT TERM

printf 'KEY=replace-with-beszel-public-key\nTOKEN=replace-with-beszel-agent-token\n' >"$TMP/agent.env"
: >"$TMP/production-metrics-token"
printf ':8080 {\n\tlog\n\t@metrics_auth {\n\t\tpath /metrics\n\t\theader Authorization "Bearer rehearsal-metrics-token"\n\t}\n\t@metrics {\n\t\tpath /metrics\n\t}\n\thandle @metrics_auth {\n\t\troot * /srv\n\t\tfile_server\n\t}\n\thandle @metrics {\n\t\trespond 401\n\t}\n\trespond /health/ready 200\n\troot * /srv\n\tfile_server\n}\n' >"$TMP/mock.Caddyfile"
printf 'up 1\n' >"$TMP/metrics"

docker network create "$NETWORK" >/dev/null
for spec in \
    "$MOCK_BACKEND|geoguessme-production" \
    "$MOCK_DEV|geoguessme-dev"; do
    name=${spec%%|*}
    label=${spec##*|}
    port=18081
    network_alias=backend
    [ "$name" = "$MOCK_DEV" ] && port=18082
    [ "$name" = "$MOCK_DEV" ] && network_alias=dev-backend
    docker run -d --name "$name" \
        --label "com.docker.compose.project=$label" \
        --network "$NETWORK" --network-alias "$network_alias" \
        --publish "127.0.0.1:${port}:8080" \
        --read-only --tmpfs /tmp:size=16m,noexec,nosuid,nodev \
        --tmpfs /data:size=16m,noexec,nosuid,nodev \
        --tmpfs /config:size=16m,noexec,nosuid,nodev \
        --mount "type=bind,src=$TMP/mock.Caddyfile,dst=/etc/caddy/Caddyfile,ro" \
        --mount "type=bind,src=$TMP/metrics,dst=/srv/metrics,ro" \
        geoguessme-web:local \
        caddy run --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null
done

export WEB_IMAGE=geoguessme-web:local
export GEOGUESSME_WATCH_METRICS_DIR="$TMP"
export GEOGUESSME_WATCH_AGENT_ENV="$TMP/agent.env"
export GEOGUESSME_PRODUCTION_FRONTEND_NETWORK="$NETWORK"
export GEOGUESSME_WATCH_PORT=18084
export GEOGUESSME_WATCH_DOCKER_PROXY_PORT=12375

compose() {
    docker compose -p "$PROJECT" -f "$WATCH_COMPOSE" --project-directory "$ROOT/deployment" "$@"
}

# Beszel agent credentials are generated by a live Hub and cannot be fabricated
# for a disposable run. Its image, socket wiring, and required env-file path
# are still validated by Compose and the repository contract tests below.
compose up -d gateway socket-proxy victoria-logs victoria-metrics vector >/dev/null

ready=0
for _ in $(seq 1 60); do
    if curl --fail --silent --max-time 2 http://127.0.0.1:18084/api/health >/dev/null &&
        curl --fail --silent --max-time 2 http://127.0.0.1:18084/logs/-/healthy >/dev/null &&
        curl --fail --silent --max-time 2 http://127.0.0.1:18084/metrics/-/healthy >/dev/null; then
        ready=1
        break
    fi
    sleep 1
done
[ "$ready" -eq 1 ] || {
    echo 'watch rehearsal services did not become ready' >&2
    exit 1
}

curl --fail --silent --show-error http://127.0.0.1:18081/health/ready >/dev/null
unauthorized_metric=$(curl --silent --show-error --max-time 2 -o /dev/null -w '%{http_code}' http://127.0.0.1:18081/metrics)
[ "$unauthorized_metric" = 401 ] || {
    echo "mock production metrics endpoint accepted an unauthenticated request: $unauthorized_metric" >&2
    exit 1
}
docker restart "$MOCK_BACKEND" >/dev/null

metric_ok=0
metric_denied=0
log_ok=0
# VictoriaMetrics scrapes every 30 seconds; allow one full interval plus
# startup slack for a busy Docker host before declaring the target absent.
for _ in $(seq 1 90); do
    metric_response=$(curl --fail --silent --max-time 2 -G \
        --data-urlencode 'query=up{job="geoguessme-production"}' \
        http://127.0.0.1:18084/metrics/api/v1/query 2>/dev/null || true)
    log_response=$(curl --fail --silent --max-time 2 -G \
        --data-urlencode "query=container_name:$MOCK_BACKEND _time:5m" \
        http://127.0.0.1:18084/logs/select/logsql/query 2>/dev/null || true)
    if printf '%s' "$metric_response" | grep -Fq '"0"'; then
        metric_denied=1
        printf 'rehearsal-metrics-token\n' >"$TMP/production-metrics-token"
    fi
    printf '%s' "$metric_response" | grep -Fq '"1"' && metric_ok=1
    printf '%s' "$log_response" | grep -Fq '"_msg"' && log_ok=1
    [ "$metric_ok" -eq 1 ] && [ "$log_ok" -eq 1 ] && break
    sleep 1
done
[ "$metric_denied" -eq 1 ] || {
    echo 'VictoriaMetrics did not show the bearer-protected target as down without a token' >&2
    exit 1
}
[ "$metric_ok" -eq 1 ] || {
    echo 'VictoriaMetrics did not scrape the production-labelled backend' >&2
    exit 1
}
[ "$log_ok" -eq 1 ] || {
    echo 'Vector did not forward production backend logs' >&2
    exit 1
}

dev_response=$(curl --fail --silent --max-time 2 -G \
    --data-urlencode "query=container_name:$MOCK_DEV _time:5m" \
    http://127.0.0.1:18084/logs/select/logsql/query)
if printf '%s' "$dev_response" | grep -Fq '"_msg"'; then
    echo 'Vector forwarded a development-labelled container' >&2
    exit 1
fi

published=$(docker port "$PROJECT-gateway-1" 80/tcp)
printf '%s' "$published" | grep -Fq '127.0.0.1:18084' || {
    echo "watch gateway is not loopback-bound: $published" >&2
    exit 1
}

echo 'watch rehearsal passed'
