#!/bin/sh
set -eu

web_image="${WEB_IMAGE:-${LOCAL_WEB_IMAGE:?LOCAL_WEB_IMAGE must be exported by Make}}"
WEB_IMAGE=$(docker image inspect --format '{{.Id}}' "$web_image")
printf '%s\n' "$WEB_IMAGE" | grep -Eq '^sha256:[0-9a-f]{64}$' || {
    echo "watch rehearsal could not resolve an immutable image ID: $web_image" >&2
    exit 1
}
export WEB_IMAGE

ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/../../.." && pwd)
WATCH_COMPOSE="$ROOT/deployment/compose.watch.yaml"
PROJECT="${GEOGUESSME_WATCH_PROJECT:-geoguessme-watch-rehearsal-${GEOGUESSME_TOOLS_PROJECT:?Run through Make}-$$}"
NETWORK="geoguessme-watch-production-${GEOGUESSME_TOOLS_PROJECT}-$$"
PRODUCTION_MOCK_PORT="${GEOGUESSME_WATCH_PRODUCTION_MOCK_PORT:-$((${GEOGUESSME_TEST_PORT_BASE:?Run through Make} + 6))}"
DEV_MOCK_PORT="${GEOGUESSME_WATCH_DEV_MOCK_PORT:-$((${GEOGUESSME_TEST_PORT_BASE:?Run through Make} + 7))}"
GEOGUESSME_WATCH_PORT="${GEOGUESSME_WATCH_PORT:-$((${GEOGUESSME_TEST_PORT_BASE:?Run through Make} + 8))}"
GEOGUESSME_WATCH_DOCKER_PROXY_PORT="${GEOGUESSME_WATCH_DOCKER_PROXY_PORT:-$((${GEOGUESSME_TEST_PORT_BASE:?Run through Make} + 9))}"
TMP=$(mktemp -d)
chmod 0755 "$TMP"
MOCK_BACKEND="geoguessme-production-backend-rehearsal-${GEOGUESSME_TOOLS_PROJECT}-$$"
MOCK_DEV="geoguessme-dev-backend-rehearsal-${GEOGUESSME_TOOLS_PROJECT}-$$"
SOCKET_PROXY_IMAGE=${SOCKET_PROXY_IMAGE:-geoguessme/socket-proxy-tools:local}
export SOCKET_PROXY_IMAGE
export GEOGUESSME_WATCH_METRICS_DIR="$TMP"
export GEOGUESSME_WATCH_AGENT_ENV="$TMP/agent.env"
export GEOGUESSME_PRODUCTION_FRONTEND_NETWORK="$NETWORK"
export GEOGUESSME_WATCH_PORT GEOGUESSME_WATCH_DOCKER_PROXY_PORT

compose() {
    docker compose -p "$PROJECT" -f "$WATCH_COMPOSE" -f "$TMP/override.yaml" \
        --project-directory "$ROOT/deployment" "$@"
}

cleanup() {
    status=$?
    cleanup_status=0
    if [ -f "$TMP/override.yaml" ]; then
        if [ "$status" -ne 0 ]; then
            # All bind configurations/environment files are fake fixture-only.
            # Never inspect Config.Env, dump whole containers, or query a peer project.
            echo "watch rehearsal failed; diagnostics for managed project $PROJECT" >&2
            compose ps --all || echo 'watch fixture status diagnostic failed' >&2
            compose logs --no-color --tail 100 || echo 'watch fixture logs diagnostic failed' >&2
            ids=$(compose ps -aq) || ids=''
            for id in $ids; do
                docker inspect --format '{{.Name}} status={{.State.Status}} health={{json .State.Health}}' "$id" ||
                    echo 'watch fixture health diagnostic failed' >&2
            done
        fi
        compose down -v --remove-orphans || cleanup_status=$?
    fi
    docker rm -f "$MOCK_BACKEND" "$MOCK_DEV" >/dev/null 2>&1 || cleanup_status=1
    docker network rm "$NETWORK" >/dev/null 2>&1 || cleanup_status=1
    rm -rf "${TMP:?}" || cleanup_status=1
    if [ "$cleanup_status" -ne 0 ]; then
        echo "watch rehearsal cleanup failed for managed project $PROJECT" >&2
    fi
    if [ "$status" -eq 0 ]; then status=$cleanup_status; fi
    exit "$status"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

# shellcheck source=deployment/scripts/watch/prepare-rehearsal.sh
. "$ROOT/deployment/scripts/watch/prepare-rehearsal.sh"
prepare_watch_fixture "$ROOT" "$TMP" "$MOCK_BACKEND" "$MOCK_DEV"

docker network create "$NETWORK" >/dev/null
for spec in \
    "$MOCK_BACKEND|geoguessme-production" \
    "$MOCK_DEV|geoguessme-dev"; do
    name=${spec%%|*}
    label=${spec##*|}
    port=$PRODUCTION_MOCK_PORT
    network_alias=backend
    [ "$name" = "$MOCK_DEV" ] && port=$DEV_MOCK_PORT
    [ "$name" = "$MOCK_DEV" ] && network_alias=dev-backend
    docker run -d --name "$name" \
        --label "com.docker.compose.project=$label" \
        --network "$NETWORK" --network-alias "$network_alias" \
        --publish "127.0.0.1:${port}:8080" \
        --read-only --tmpfs /tmp:size=16m,noexec,nosuid,nodev \
        --tmpfs /data:size=16m,noexec,nosuid,nodev \
        --tmpfs /config:size=16m,noexec,nosuid,nodev \
        --mount "type=bind,src=$TMP/mock.Caddyfile,dst=/etc/caddy/Caddyfile,ro" \
        --mount "type=bind,src=$TMP/metrics,dst=/srv/metrics,ro" \
        "$WEB_IMAGE" \
        caddy run --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null
done

# Beszel agent credentials are generated by a live Hub and cannot be fabricated
# for a disposable run. Its image, socket wiring, and required env-file path
# are still validated by Compose and the repository contract tests below.
compose up -d gateway socket-proxy victoria-logs victoria-metrics vector >/dev/null

ready=0
for _ in $(seq 1 60); do
    if curl --fail --silent --max-time 2 "http://127.0.0.1:${GEOGUESSME_WATCH_PORT}"/api/health >/dev/null &&
        curl --fail --silent --max-time 2 "http://127.0.0.1:${GEOGUESSME_WATCH_PORT}"/logs/-/healthy >/dev/null &&
        curl --fail --silent --max-time 2 "http://127.0.0.1:${GEOGUESSME_WATCH_PORT}"/metrics/-/healthy >/dev/null; then
        ready=1
        break
    fi
    sleep 1
done
[ "$ready" -eq 1 ] || {
    echo 'watch rehearsal services did not become ready' >&2
    exit 1
}

curl --fail --silent --show-error "http://127.0.0.1:${PRODUCTION_MOCK_PORT}"/health/ready >/dev/null
unauthorized_metric=$(curl --silent --show-error --max-time 2 -o /dev/null -w '%{http_code}' "http://127.0.0.1:${PRODUCTION_MOCK_PORT}"/metrics)
[ "$unauthorized_metric" = 401 ] || {
    echo "mock production metrics endpoint accepted an unauthenticated request: $unauthorized_metric" >&2
    exit 1
}
docker restart "$MOCK_BACKEND" >/dev/null

metric_ok=0
metric_denied=0
log_ok=0
# VictoriaMetrics scrapes every 30 seconds; allow one full interval plus
# startup slack for a busy Docker host before declaring the target absent.
for _ in $(seq 1 90); do
    metric_response=$(curl --fail --silent --max-time 2 -G \
        --data-urlencode 'query=up{job="geoguessme-production"}' \
        "http://127.0.0.1:${GEOGUESSME_WATCH_PORT}"/metrics/api/v1/query 2>/dev/null || true)
    log_response=$(curl --fail --silent --max-time 2 -G \
        --data-urlencode "query=container_name:$MOCK_BACKEND _time:5m" \
        "http://127.0.0.1:${GEOGUESSME_WATCH_PORT}"/logs/select/logsql/query 2>/dev/null || true)
    if printf '%s' "$metric_response" | grep -Fq '"0"'; then
        metric_denied=1
        printf 'rehearsal-metrics-token\n' >"$TMP/production-metrics-token"
    fi
    printf '%s' "$metric_response" | grep -Fq '"1"' && metric_ok=1
    printf '%s' "$log_response" | grep -Fq '"_msg"' && log_ok=1
    [ "$metric_ok" -eq 1 ] && [ "$log_ok" -eq 1 ] && break
    sleep 1
done
[ "$metric_denied" -eq 1 ] || {
    echo 'VictoriaMetrics did not show the bearer-protected target as down without a token' >&2
    exit 1
}
[ "$metric_ok" -eq 1 ] || {
    echo 'VictoriaMetrics did not scrape the production-labelled backend' >&2
    exit 1
}
[ "$log_ok" -eq 1 ] || {
    echo 'Vector did not forward production backend logs' >&2
    exit 1
}

dev_response=$(curl --fail --silent --max-time 2 -G \
    --data-urlencode "query=container_name:$MOCK_DEV _time:5m" \
    "http://127.0.0.1:${GEOGUESSME_WATCH_PORT}"/logs/select/logsql/query)
if printf '%s' "$dev_response" | grep -Fq '"_msg"'; then
    echo 'Vector forwarded a development-labelled container' >&2
    exit 1
fi

published=$(docker port "$PROJECT-gateway-1" 80/tcp)
printf '%s' "$published" | grep -Fq "127.0.0.1:${GEOGUESSME_WATCH_PORT}" || {
    echo "watch gateway is not loopback-bound: $published" >&2
    exit 1
}

echo 'watch rehearsal passed'
