// GENERATED FILE
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/auth/signup': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a legacy account when Keycloak is disabled.
         * @description Normal signup uses Keycloak. This compatibility endpoint returns 410 while OIDC is enabled.
         */
        post: operations['signup'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/login': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a temporary legacy migration session.
         * @description Hidden from normal login; accepts only an unmigrated legacy account and issues a read-only session while OIDC is enabled.
         */
        post: operations['login'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/oidc/config': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether Keycloak sign-in is enabled. */
        get: operations['getOIDCConfig'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/oidc/session': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange the OAuth2 Proxy Keycloak session for an application session.
         * @description Keycloak tokens are forwarded server-to-server by OAuth2 Proxy and are never returned to browser JavaScript. A genuinely new identity receives username_required until it submits an explicit GeoGuessMe username; existing identities and verified-email migrations do not need one.
         */
        post: operations['exchangeOIDCSession'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/oidc/link': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start linking Keycloak to the authenticated application account. */
        post: operations['startOIDCLink'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/refresh': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate the refresh session. */
        post: operations['refreshSession'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/logout': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a session. */
        post: operations['logout'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/verify/request': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request email verification. */
        post: operations['requestVerification'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/verify': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an email address with a token. */
        post: operations['verifyEmail'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/password/forgot': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a password reset. */
        post: operations['forgotPassword'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/password/reset': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset a password with a token. */
        post: operations['resetPassword'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/password/change': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the authenticated user's password. */
        post: operations['changePassword'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/profile': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user's profile and progression. */
        get: operations['getProfile'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the authenticated user's profile. */
        patch: operations['updateProfile'];
        trace?: never;
    };
    '/auth/profile/avatar': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a profile photo.
         * @description Accepts JPG, PNG, and WebP uploads up to 25 MiB. The web client sends the original selected file; the backend validates the image bytes, strips metadata, and resizes the result to a 256-pixel maximum dimension.
         */
        post: operations['uploadAvatar'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/account': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete the authenticated account. */
        delete: operations['deleteAccount'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/user/groups': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's groups. */
        get: operations['listUserGroups'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/user/profile/{userID}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get another player's progression profile.
         * @description Returns a player's identity and progression. The player must share at least one group with the requester, or be the requester themselves; email and account details are never returned.
         */
        get: operations['getUserProfile'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/create': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a group. */
        post: operations['createGroup'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/join': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a group with an invite token. */
        post: operations['joinGroup'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/invites': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the invites of a group for a current member. */
        get: operations['listInvites'];
        put?: never;
        /** Create a group invite; returns the bearer token exactly once. */
        post: operations['createInvite'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/invites/preview': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview a group from an invite token without authenticating.
         * @description Public endpoint. The token travels in the JSON body so it never appears in a URL, path, or access log. Unknown, expired, and revoked tokens all return the same generic 404.
         */
        post: operations['previewInvite'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/invites/{inviteID}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a group invite immediately. */
        delete: operations['revokeInvite'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/details': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get group details. */
        get: operations['getGroupDetails'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/members': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List group members. */
        get: operations['listGroupMembers'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/leaderboard': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the group leaderboard. */
        get: operations['getLeaderboard'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/photo': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream the private photo for a group. */
        get: operations['getGroupPhoto'];
        put?: never;
        /** Replace the authenticated member's group photo. */
        post: operations['uploadGroupPhoto'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/notifications': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated member's notification preference for a group. */
        get: operations['getGroupNotificationPreference'];
        /** Enable or disable notifications for the authenticated member in a group. */
        put: operations['setGroupNotificationPreference'];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/messages': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cursor-paginated group messages. */
        get: operations['listGroupMessages'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/reaction-usage': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get aggregate reaction usage for a group.
         * @description Returns counts for reactions used in the group, ordered by popularity.
         */
        get: operations['getGroupReactionUsage'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/message-reactions/{messageID}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Add a reaction to a group message. */
        put: operations['setMessageReaction'];
        post?: never;
        /** Remove the authenticated user's reaction. */
        delete: operations['removeMessageReaction'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/messages/media': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a private image or recorded video in group chat. */
        post: operations['uploadGroupMessageMedia'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/group/messages/media/{mediaID}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream a private chat attachment for a current group member. */
        get: operations['getGroupMessageMedia'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/photo/upload': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a photo or camera-recorded video challenge to one or more groups. */
        post: operations['uploadPhotoChallenge'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/media-processing/{jobID}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the owner-only status of an asynchronous media-processing job. */
        get: operations['getMediaProcessingJob'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/challenges/{photoID}/accept': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a challenge and start its private view window. */
        post: operations['acceptChallenge'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/challenges/{photoID}/media': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream challenge media during an authorized window or result view. */
        get: operations['getChallengeMedia'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/challenges/{photoID}/media-delivered': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm complete media delivery and start the private view window. */
        post: operations['confirmChallengeMediaDelivered'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/challenges/{photoID}/guess': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit one guess after the private view window. */
        post: operations['submitChallengeGuess'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/challenges/{photoID}/results': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authorized challenge results. */
        get: operations['getChallengeResults'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/ws/ticket': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a one-time WebSocket ticket. */
        post: operations['createWebSocketTicket'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/ws': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Upgrade to the authenticated group chat WebSocket.
         * @description Request a ticket with POST /ws/ticket, then connect with the returned
         *     ticket. The ticket is single-use, expires quickly, and the server rejects
         *     origins that are not in ALLOWED_ORIGINS.
         */
        get: operations['connectWebSocketChat'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/push/vapid-public-key': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the active VAPID public key */
        get: operations['getVapidPublicKey'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/push/subscribe': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Store a push subscription */
        post: operations['subscribe'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/push/unsubscribe': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a push subscription */
        delete: operations['unsubscribe'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthUser: {
            /** Format: uuid */
            id: string;
            username: string;
            /**
             * Format: email
             * @description The verified contact address, present only after the account has verified a claim. Email is a recovery/contact channel, not an authorization identity; an unverified account simply has no email.
             */
            email?: string | null;
            /**
             * Format: email
             * @description The current unverified contact claim. The verified email stays active until this claim is successfully verified.
             */
            pending_email?: string;
            /** Format: date-time */
            email_verified_at?: string | null;
            avatar?: string;
            /** @description Whether the hidden migration flow may still confirm this legacy account's password. */
            password_login_enabled: boolean;
            /** @description Whether the account is linked to the configured Keycloak realm. */
            oidc_linked: boolean;
            /** @description Whether the legacy account is read-only until a Keycloak identity is linked. */
            migration_required: boolean;
        };
        AuthResponse: {
            access_token: string;
            expires_in: number;
            user: components['schemas']['AuthUser'];
        };
        APIError: {
            error: {
                code: string;
                message: string;
            };
        };
        OIDCConfig: {
            enabled: boolean;
            login_path: string;
            /**
             * Format: uri
             * @description Runtime-specific Keycloak account console used for optional 2FA, recovery codes, and passkeys.
             */
            account_url?: string;
            /** @description Social brokers configured in this environment; email/password is always handled by Keycloak. */
            social_providers: ('google' | 'apple' | 'github')[];
        };
        ProgressionRank: {
            level: number;
            name: string;
            min_points: number;
            next_points?: number;
            points_in_rank: number;
            points_to_next: number;
            progress_percent: number;
            trophy_key: string;
            /** @description The following rank, omitted at the highest rank. */
            next_rank?: components['schemas']['ProgressionRank'];
        };
        GlobalRank: {
            /** @description Position among every player who has guessed at least once, ordered by lifetime points using standard competition ranking. Zero while the player has no guesses of their own. */
            rank: number;
            /** @description Number of players who have guessed at least once. */
            total_players: number;
        };
        Profile: components['schemas']['AuthUser'] & {
            total_points: number;
            guess_count: number;
            average_score: number;
            /** @description Global all-time Elo rating, updated with a small factor so it reflects long-run skill; 0 while never compared against another guesser. */
            elo: number;
            rank: components['schemas']['ProgressionRank'];
            global_rank: components['schemas']['GlobalRank'];
            global_average_rank: components['schemas']['GlobalRank'];
            global_elo_rank: components['schemas']['GlobalRank'];
        };
        Group: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Another player's progression profile. Never contains email or account details; only visible when the player shares a group with the requester. */
        PublicProfile: {
            id: string;
            username: string;
            avatar: string;
            total_points: number;
            guess_count: number;
            average_score: number;
            elo: number;
            rank: components['schemas']['ProgressionRank'];
            global_rank: components['schemas']['GlobalRank'];
            global_average_rank: components['schemas']['GlobalRank'];
            global_elo_rank: components['schemas']['GlobalRank'];
        };
        /** @description Canonical 32-byte base64url bearer token from a group invite link. */
        InviteToken: string;
        InviteListItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            creator_user_id: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            revoked: string | null;
        };
        InviteCreateRequest: {
            /** Format: uuid */
            group_id: string;
        };
        InviteCreateResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            token: components['schemas']['InviteToken'];
            /**
             * Format: uri-reference
             * @description Join path carrying the token in a fragment (/group/join#invite=<token>); clients prepend their origin to build a shareable link.
             */
            invite_url: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            expires_at: string;
        };
        InvitePreviewRequest: {
            invite_token: components['schemas']['InviteToken'];
        };
        InvitePreview: {
            group_name: string;
            member_count: number;
        };
        Member: {
            /** Format: uuid */
            id: string;
            username: string;
            avatar?: string;
        };
        LeaderboardEntry: {
            /** Format: uuid */
            user_id: string;
            username: string;
            avatar: string;
            /** @description Sum of all guess scores in the selected period. */
            score: number;
            guess_count: number;
            /** @description Average guess score in the selected period. */
            average_score: number;
            /** @description Lifetime guess points used for rank progression. */
            total_points: number;
            /** @description Elo rating computed from the selected period's challenges; 0 while the player never compared against another guesser on a shared challenge in the period. The update factor depends on the period: weekly ladders move fastest, monthly moderately, and all-time slowest. */
            elo: number;
            rank: components['schemas']['ProgressionRank'];
        };
        GroupPhoto: {
            /** Format: uuid */
            group_id: string;
            /** @enum {string} */
            mime_type: 'image/jpeg';
            byte_size: number;
            /** Format: date-time */
            created_at: string;
        };
        GroupNotificationPreference: {
            enabled: boolean;
        };
        /**
         * @description Reaction identity. The twenty-four named keys map to custom artwork shown in the UI; the six legacy emoji values are still accepted so existing reactions keep working.
         * @enum {string}
         */
        ReactionKey:
            | 'like'
            | 'love'
            | 'laugh'
            | 'wow'
            | 'sad'
            | 'spot-on'
            | 'lost'
            | 'mind-blown'
            | 'wrong-way'
            | 'vacation'
            | 'dislike'
            | 'cry'
            | 'kiss'
            | 'wink'
            | 'grin'
            | 'heart-eyes'
            | 'sunglasses'
            | 'angry'
            | 'confused'
            | 'sleepy'
            | 'clap'
            | 'pray'
            | 'fire'
            | 'party'
            | '👍'
            | '❤️'
            | '😂'
            | '😮'
            | '😢'
            | '🙏';
        MessageReaction: {
            reaction: components['schemas']['ReactionKey'];
            count: number;
            /** @description Whether the authenticated viewer selected this reaction */
            reacted: boolean;
            /** @description Usernames of group members who selected this reaction */
            usernames: string[];
        };
        /** @description WebSocket-only reaction mutation metadata used to preserve each recipient's viewer-specific state. */
        MessageReactionUpdate: {
            /** Format: uuid */
            user_id: string;
            reaction: components['schemas']['ReactionKey'];
            active: boolean;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            /** Format: uuid */
            user_id: string;
            username?: string;
            avatar?: string;
            /** @enum {string} */
            kind: 'text' | 'challenge' | 'media' | 'system';
            /** Format: uuid */
            photo_id?: string | null;
            /** Format: uuid */
            media_id?: string | null;
            /** @enum {string} */
            media_type?: 'image/jpeg' | 'image/png' | 'video/mp4' | 'video/webm';
            /** Format: uuid */
            reply_to_id?: string | null;
            content?: string;
            /** Format: date-time */
            created_at: string;
            /**
             * @description Viewer-specific action state for challenge messages
             * @enum {string}
             */
            challenge_status?: 'available' | 'accepted' | 'guessed' | 'results' | 'expired';
            /** @description Whether any group member has answered the challenge */
            challenge_resolved?: boolean;
            /**
             * Format: date-time
             * @description Challenge deadline (upload time + TTL), present on challenge messages.
             */
            challenge_expires_at?: string;
            /** @description Challenge duration in seconds, present on challenge messages. */
            challenge_ttl_seconds?: number;
            reactions?: components['schemas']['MessageReaction'][];
            reaction_update?: components['schemas']['MessageReactionUpdate'];
        };
        MessagesPage: {
            items: components['schemas']['Message'][];
            next_cursor?: string | null;
            /** @description Opaque cursor strictly after the last message of the page; the reconnect catch-up anchor (empty for an empty page) */
            stable_cursor?: string | null;
        };
        ReactionUsage: {
            reaction: components['schemas']['ReactionKey'];
            count: number;
        };
        /** @description Supply the reaction key to set or remove. */
        MessageReactionRequest: {
            reaction: components['schemas']['ReactionKey'];
        };
        ChallengeCreated: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            server_time: string;
        };
        /** @description Owner-only status of an asynchronous video-processing job. Storage keys and upload metadata are never serialized. */
        MediaProcessingJob: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: 'challenge' | 'chat';
            /** @enum {string} */
            status: 'queued' | 'processing' | 'ready' | 'failed';
            /** Format: date-time */
            queued_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** @description Present when the job is ready; the challenge record or the chat message the synchronous upload path would have returned. */
            result?: components['schemas']['ChallengeCreated'] | components['schemas']['Message'];
            /** @description Stable, non-sensitive failure code (for example invalid_video, authorization_revoked, output_too_large, or transcode_failed); present only when the job failed. */
            error_code?: string;
        };
        ChallengeAccepted: {
            /** Format: uuid */
            photo_id: string;
            media_url: string;
            /** @enum {string} */
            media_type: 'image/jpeg' | 'image/png' | 'video/mp4' | 'video/webm';
            /** Format: date-time */
            accepted_at: string;
            /** Format: date-time */
            view_expires_at: string;
            /** Format: date-time */
            guess_after: string;
            /**
             * Format: date-time
             * @description Server-authoritative deadline for submitting the guess; guessing is refused after this instant even when the client lost its timer
             */
            guess_expires_at: string;
            /** Format: date-time */
            challenge_expires_at: string;
            /** Format: date-time */
            server_time: string;
        };
        ChallengeMediaDelivered: {
            /** Format: date-time */
            view_expires_at: string;
            /** Format: date-time */
            guess_after: string;
            /**
             * Format: date-time
             * @description Server-authoritative deadline for submitting the guess; guessing is refused after this instant even when the client lost its timer
             */
            guess_expires_at: string;
            /** Format: date-time */
            server_time: string;
        };
        GuessResponse: {
            /** Format: uuid */
            guess_id: string;
            /** Format: uuid */
            photo_id: string;
            score: number;
            distance: number;
            /** Format: date-time */
            created_at: string;
            duplicate: boolean;
            /** Format: date-time */
            server_time: string;
        };
        Guess: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            photo_id: string;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            group_id: string;
            /**
             * Format: double
             * @description Omitted for other players' guesses while a hidden-location challenge is still hidden; only the viewer's own guessed point is returned.
             */
            lat?: number;
            /**
             * Format: double
             * @description Omitted alongside lat while the location is hidden.
             */
            long?: number;
            score: number;
            /** @description Signed change in the player's weekly Elo rating caused by this challenge; zero when the challenge has fewer than two guesses or was created before the current calendar week started. */
            elo_delta: number;
            /** @description Omitted alongside the coordinates while the location is hidden. */
            distance?: number;
            /** Format: date-time */
            created_at: string;
            username?: string;
            avatar?: string;
        };
        ChallengeResults: {
            /** Format: uuid */
            photo_id: string;
            /** Format: uuid */
            group_id: string;
            /**
             * Format: double
             * @description Omitted while the poster hides the location
             */
            actual_lat?: number;
            /**
             * Format: double
             * @description Omitted while the poster hides the location
             */
            actual_long?: number;
            /** @description True when the poster hid the location and it is not yet revealed */
            location_hidden?: boolean;
            /**
             * Format: date-time
             * @description When the hidden location becomes visible on the results page
             */
            location_reveals_at?: string;
            guesses: components['schemas']['Guess'][];
            media_available: boolean;
            media_url?: string | null;
            /** @enum {string|null} */
            media_type?: 'image/jpeg' | 'image/png' | 'video/mp4' | 'video/webm' | null;
            /** Format: date-time */
            server_time: string;
        };
        PushSubscriptionRequest: {
            /** Format: uri */
            endpoint: string;
            keys: {
                /** @description Base64url 65-byte uncompressed P-256 public key */
                p256dh: string;
                /** @description Base64url 16-byte authentication secret */
                auth: string;
            };
        };
    };
    responses: {
        /** @description Structured API error. */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                'application/json': components['schemas']['APIError'];
            };
        };
    };
    parameters: {
        photoID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    username: string;
                    /**
                     * Format: email
                     * @description Optional recovery/contact claim.
                     */
                    email?: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Account created and session issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AuthResponse'];
                };
            };
            400: components['responses']['ErrorResponse'];
            409: components['responses']['ErrorResponse'];
            410: components['responses']['ErrorResponse'];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Session issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AuthResponse'];
                };
            };
            401: components['responses']['ErrorResponse'];
        };
    };
    getOIDCConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime identity capability. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['OIDCConfig'];
                };
            };
            405: components['responses']['ErrorResponse'];
        };
    };
    exchangeOIDCSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                'application/json': {
                    username?: string;
                };
            };
        };
        responses: {
            /** @description Existing identity resolved, verified-email account linked, or new account provisioned with its chosen username. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AuthResponse'];
                };
            };
            400: components['responses']['ErrorResponse'];
            401: components['responses']['ErrorResponse'];
            409: components['responses']['ErrorResponse'];
            503: components['responses']['ErrorResponse'];
        };
    };
    startOIDCLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Single-use link intent stored in an HttpOnly cookie. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components['responses']['ErrorResponse'];
            503: components['responses']['ErrorResponse'];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens rotated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AuthResponse'];
                };
            };
            401: components['responses']['ErrorResponse'];
        };
    };
    logout: {
        parameters: {
            query?: {
                all?: '1';
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components['responses']['ErrorResponse'];
        };
    };
    requestVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification email sent if the account can receive mail. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components['responses']['ErrorResponse'];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    token: string;
                };
            };
        };
        responses: {
            /** @description Email verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components['responses']['ErrorResponse'];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Reset link sent if the email is registered. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components['responses']['ErrorResponse'];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    token: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Password reset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components['responses']['ErrorResponse'];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    current_password: string;
                    new_password: string;
                };
            };
        };
        responses: {
            /** @description Password changed; all sessions are revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components['responses']['ErrorResponse'];
            401: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile, lifetime score, guess count, and current rank. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Profile'];
                };
            };
            401: components['responses']['ErrorResponse'];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    username: string;
                    /**
                     * Format: email
                     * @description Optional replacement contact claim; omission cancels a pending replacement without removing the verified address.
                     */
                    email?: string;
                    /** @enum {string} */
                    avatar:
                        | 'avatar.png'
                        | 'avatar2.png'
                        | 'avatar3.png'
                        | 'avatar4.png'
                        | 'avatar5.png'
                        | 'avatar6.png'
                        | 'avatar7.png'
                        | 'avatar8.png'
                        | 'avatar9.png'
                        | 'avatar10.png';
                    /** @description Required when password_login_enabled is true; omitted for passwordless social accounts. */
                    current_password?: string;
                };
            };
        };
        responses: {
            /** @description Updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AuthUser'];
                };
            };
            400: components['responses']['ErrorResponse'];
            401: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
            409: components['responses']['ErrorResponse'];
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'multipart/form-data': {
                    /** Format: binary */
                    photo: string;
                };
            };
        };
        responses: {
            /** @description Updated profile with the custom avatar marker. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AuthUser'];
                };
            };
            400: components['responses']['ErrorResponse'];
            401: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    /** @description Required for accounts with legacy password login enabled. */
                    password?: string;
                    /** @description Exact username required for passwordless social accounts. */
                    confirmation?: string;
                };
            };
        };
        responses: {
            /** @description Account deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components['responses']['ErrorResponse'];
        };
    };
    listUserGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Groups. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Group'][];
                };
            };
            401: components['responses']['ErrorResponse'];
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Player progression profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['PublicProfile'];
                };
            };
            401: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
            404: components['responses']['ErrorResponse'];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Group created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Group'];
                };
            };
            400: components['responses']['ErrorResponse'];
        };
    };
    joinGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    invite_token: components['schemas']['InviteToken'];
                };
            };
        };
        responses: {
            /** @description Joined group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Group'];
                };
            };
            400: components['responses']['ErrorResponse'];
            404: components['responses']['ErrorResponse'];
            410: components['responses']['ErrorResponse'];
        };
    };
    listInvites: {
        parameters: {
            query: {
                group_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invites. Never contains the bearer token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InviteListItem'][];
                };
            };
            403: components['responses']['ErrorResponse'];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InviteCreateRequest'];
            };
        };
        responses: {
            /** @description Invite created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InviteCreateResponse'];
                };
            };
            403: components['responses']['ErrorResponse'];
            409: components['responses']['ErrorResponse'];
            429: components['responses']['ErrorResponse'];
        };
    };
    previewInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['InvitePreviewRequest'];
            };
        };
        responses: {
            /** @description Non-sensitive group preview. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['InvitePreview'];
                };
            };
            400: components['responses']['ErrorResponse'];
            404: components['responses']['ErrorResponse'];
            429: components['responses']['ErrorResponse'];
        };
    };
    revokeInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inviteID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invite revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components['responses']['ErrorResponse'];
            404: components['responses']['ErrorResponse'];
        };
    };
    getGroupDetails: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Group'];
                };
            };
            403: components['responses']['ErrorResponse'];
        };
    };
    listGroupMembers: {
        parameters: {
            query: {
                id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Members. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Member'][];
                };
            };
            403: components['responses']['ErrorResponse'];
        };
    };
    getLeaderboard: {
        parameters: {
            query: {
                group_id: string;
                /** @description Calendar period in UTC. Omit for all time. */
                period?: 'week' | 'month' | 'all';
                /** @description Ranking metric. Omit for total. */
                metric?: 'total' | 'average' | 'elo';
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Leaderboard. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['LeaderboardEntry'][];
                };
            };
            403: components['responses']['ErrorResponse'];
        };
    };
    getGroupPhoto: {
        parameters: {
            query: {
                group_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG group photo bytes; Cache-Control is private, no-store. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components['responses']['ErrorResponse'];
            404: components['responses']['ErrorResponse'];
        };
    };
    uploadGroupPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'multipart/form-data': {
                    /** Format: uuid */
                    group_id: string;
                    /** Format: binary */
                    photo: string;
                };
            };
        };
        responses: {
            /** @description Group photo metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GroupPhoto'];
                };
            };
            400: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
        };
    };
    getGroupNotificationPreference: {
        parameters: {
            query: {
                group_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notification preference. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GroupNotificationPreference'];
                };
            };
            403: components['responses']['ErrorResponse'];
        };
    };
    setGroupNotificationPreference: {
        parameters: {
            query: {
                group_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['GroupNotificationPreference'];
            };
        };
        responses: {
            /** @description Saved notification preference. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GroupNotificationPreference'];
                };
            };
            400: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
        };
    };
    listGroupMessages: {
        parameters: {
            query: {
                group_id: string;
                /** @description Opaque base64 cursor from a previous next_cursor; empty selects the most recent page */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Message page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['MessagesPage'];
                };
            };
            403: components['responses']['ErrorResponse'];
        };
    };
    getGroupReactionUsage: {
        parameters: {
            query: {
                group_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reaction usage counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ReactionUsage'][];
                };
            };
            400: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
        };
    };
    setMessageReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['MessageReactionRequest'];
            };
        };
        responses: {
            /** @description Updated message. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Message'];
                };
            };
            400: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
            404: components['responses']['ErrorResponse'];
        };
    };
    removeMessageReaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                messageID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['MessageReactionRequest'];
            };
        };
        responses: {
            /** @description Updated message. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Message'];
                };
            };
            400: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
            404: components['responses']['ErrorResponse'];
        };
    };
    uploadGroupMessageMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'multipart/form-data': {
                    /** Format: uuid */
                    group_id: string;
                    /** Format: binary */
                    media: string;
                    content?: string;
                    /** Format: uuid */
                    reply_to_id?: string;
                };
            };
        };
        responses: {
            /** @description Persisted media message */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Message'];
                };
            };
            /** @description Video accepted for asynchronous processing; poll the returned job at /media-processing/{id}. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['MediaProcessingJob'];
                };
            };
            400: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
        };
    };
    getGroupMessageMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image or video bytes; Cache-Control is private, no-store. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components['responses']['ErrorResponse'];
            404: components['responses']['ErrorResponse'];
        };
    };
    uploadPhotoChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'multipart/form-data': {
                    /** Format: binary */
                    photo: string;
                    /** @description Target groups (repeated form field) */
                    group_ids?: string[];
                    /** @description Hide the exact location from guessers for the configured duration (48 hours by default) */
                    hide_location?: boolean;
                    /** Format: double */
                    lat: number;
                    /** Format: double */
                    long: number;
                };
            };
        };
        responses: {
            /** @description Challenge created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ChallengeCreated'];
                };
            };
            /** @description Video accepted for asynchronous processing; poll the returned job at /media-processing/{id}. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['MediaProcessingJob'];
                };
            };
            400: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
        };
    };
    getMediaProcessingJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job status; the result is present when ready, the error_code only when failed. Storage keys and upload metadata are never exposed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['MediaProcessingJob'];
                };
            };
            400: components['responses']['ErrorResponse'];
            404: components['responses']['ErrorResponse'];
        };
    };
    acceptChallenge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photoID: components['parameters']['photoID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Challenge accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ChallengeAccepted'];
                };
            };
            403: components['responses']['ErrorResponse'];
            404: components['responses']['ErrorResponse'];
            410: components['responses']['ErrorResponse'];
        };
    };
    getChallengeMedia: {
        parameters: {
            query?: {
                result?: '1';
            };
            header?: never;
            path: {
                photoID: components['parameters']['photoID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image or video bytes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'image/jpeg': string;
                    'image/png': string;
                    'image/webp': string;
                    'video/mp4': string;
                    'video/webm': string;
                };
            };
            403: components['responses']['ErrorResponse'];
            410: components['responses']['ErrorResponse'];
        };
    };
    confirmChallengeMediaDelivered: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photoID: components['parameters']['photoID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authoritative viewing deadline. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ChallengeMediaDelivered'];
                };
            };
            403: components['responses']['ErrorResponse'];
        };
    };
    submitChallengeGuess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photoID: components['parameters']['photoID'];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    /** Format: double */
                    lat: number;
                    /** Format: double */
                    long: number;
                };
            };
        };
        responses: {
            /** @description Existing guess returned idempotently. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuessResponse'];
                };
            };
            /** @description Guess recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['GuessResponse'];
                };
            };
            403: components['responses']['ErrorResponse'];
            /** @description Viewing window is still open (viewing_window_open). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['APIError'];
                };
            };
            /** @description Guess refused: the challenge expired (challenge_expired) or the guess window elapsed (guess_time_expired — the guesser did not guess in time). */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['APIError'];
                };
            };
        };
    };
    getChallengeResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                photoID: components['parameters']['photoID'];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Challenge results. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ChallengeResults'];
                };
            };
            403: components['responses']['ErrorResponse'];
            404: components['responses']['ErrorResponse'];
        };
    };
    createWebSocketTicket: {
        parameters: {
            query: {
                group_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket issued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        ticket: string;
                        /** @example 60 */
                        expires_in: number;
                        /** Format: date-time */
                        server_time: string;
                    };
                };
            };
            403: components['responses']['ErrorResponse'];
        };
    };
    connectWebSocketChat: {
        parameters: {
            query: {
                group_id: string;
                ticket: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebSocket protocol upgrade. */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A normal HTTP response when the upgrade is not requested. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components['responses']['ErrorResponse'];
            403: components['responses']['ErrorResponse'];
        };
    };
    getVapidPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active application server public key in base64url. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @description 65-byte uncompressed P-256 point (base64url) */
                        public_key: string;
                    };
                };
            };
            401: components['responses']['ErrorResponse'];
            /** @description Push notifications are disabled (no VAPID keys configured). */
            503: components['responses']['ErrorResponse'];
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['PushSubscriptionRequest'];
            };
        };
        responses: {
            /** @description Subscription stored (upserted by user + endpoint). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** Format: uuid */
                        id: string;
                    };
                };
            };
            400: components['responses']['ErrorResponse'];
            401: components['responses']['ErrorResponse'];
            /** @description Push disabled. */
            503: components['responses']['ErrorResponse'];
        };
    };
    unsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                'application/json': {
                    /** Format: uri */
                    endpoint?: string;
                };
            };
        };
        responses: {
            /** @description Subscription(s) removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components['responses']['ErrorResponse'];
            /** @description The specified endpoint was not found. */
            404: components['responses']['ErrorResponse'];
        };
    };
}
