FROM quay.io/keycloak/keycloak:26.7.5@sha256:37dbaf6f0722c9ec246335f36e1ef8b2e6cb960f7c27e0d8c615121a3d475a85

LABEL org.opencontainers.image.base.name="quay.io/keycloak/keycloak:26.7.5" \
      org.opencontainers.image.base.digest="sha256:37dbaf6f0722c9ec246335f36e1ef8b2e6cb960f7c27e0d8c615121a3d475a85" \
      org.opencontainers.image.description="Keycloak 26.7.5"

ARG DEPENDENCY_INPUTS
LABEL dev.geoguessme.dependency-inputs="${DEPENDENCY_INPUTS}"

USER 1000
