FROM quay.io/keycloak/keycloak:26.8.0@sha256:b0f60d489d51c5d113390bdf5461d4c06e6051be026c05549f2e1e10ec352bcc

LABEL org.opencontainers.image.base.name="quay.io/keycloak/keycloak:26.8.0" \
      org.opencontainers.image.base.digest="sha256:b0f60d489d51c5d113390bdf5461d4c06e6051be026c05549f2e1e10ec352bcc" \
      org.opencontainers.image.description="Keycloak 26.8.0"

ARG DEPENDENCY_INPUTS
LABEL dev.geoguessme.dependency-inputs="${DEPENDENCY_INPUTS}"

USER 1000
